# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c5312b99034f694c5810026d43221452cb0476b13dfdcc6970a0fe5a4af5b0da99e9ac4f59abb329f90dc2c594cab5692600752d205bb4b513f8d7c46dd032d

test:
  secret_key_base: ec98cbb2edcbdc657f02623e50ea752e5a3bc0d9c18adf1b8d20ff21f4a5f5ddcf006d60a68fbff17e3aae90348bca18cafe17b3ad7a278661b45f6100760419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
